sudo: false
language: node_js
install:
  -npm install

cache: npm
branches:
  only:
    - src # build src branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: src
  local-dir: public
  